padre_papá(severino).
madre_papá(juana).
padre_mamá(carlos).
madre_mamá(natalia).
mamá(reina).
papá(jhon).
hermano_papá(celestino).
hermana_mamá(martha).
abuelo(severino).
abuela(juana).
abuela_ma(natalia).
abuelo_ma(carlo).
tio(celestino).
tia(luisa).
primo(nestor,natalio).
prima(saloma,paulina).
hijo(dayver).
hermana(justina).
hermano(isaac).

/*RELACIONES*/
hijo(dayver,jhon).
abuelo(dayver,severino,carlos).
abuela(dayver,juana,natalia).
primo(dayver,nestor).
primo(dayver,natalio).
prima(dayver,saloma).
prima(dayver,paulina).
tio(dayver,celestino).
tia(dayver,luisa).
hermana(dayver,justina).
hermano(dayver,isaac).
nieto(dayver,severino).
hombre(dayver,severino,carlos,jhon,celestino,nestor,natalio,isaac).
mujer(juana,martha,reina,natalia,luisa,justina,saloma,paulina).

